version: '3.1'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on: ["mariadb"]
    environment:
      - NODE_ENV=${NODE_ENV}
  web:
    build: ./app
    ports:
     - "8000:80"
    volumes:
      - "./app:/app:cached"
    depends_on: ["server"]
    command: npm start
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}


