version: '3.1'
services:
  server:
    build: ./server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on: ["mariadb"]
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${MYSQL_ROOT_USER}
      - DB_PORT=${MYSQL_PORT}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_HOST=${MYSQL_HOST}
      - LOG_FILE_LOCATION=${LOG_FILE_LOCATION}
      - RECEIPT_FILE_DIRECTORY=${RECEIPT_FILE_DIRECTORY}
      - ACCESS_CONTROL_ALLOW_ORIGIN=${ACCESS_CONTROL_ALLOW_ORIGIN}
      - SERVER_PORT=${SERVER_PORT}
  web:
    build: ./app
    ports:
     - "8000:80"
    volumes:
      - "./app:/app:cached"
    depends_on: ["server"]
    command: npm start
  mariadb:
    image: mariadb:10.4
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3306 || exit 1"]
      interval: 1m30s
      timeout: 60s
      retries: 6
  flyway:
    image: flyway/flyway:6.3-alpine
    command: -url=jdbc:mariadb://mariadb:${MYSQL_PORT}/${MYSQL_DATABASE} -user=${MYSQL_ROOT_USER} -password=${MYSQL_ROOT_PASSWORD} -connectRetries=60 migrate
    volumes:
      - "./sql:/flyway/sql"
    depends_on: ["mariadb"]



